In [1]:
import pyglet
from pyglet.window import mouse
from pyglet.window import key
import numpy as np
from GridControl.Environment import Environment
from GridControl.Agent import Agent

In [2]:
pyglet.canvas.get_display().get_default_screen()

Win32Screen(x=0, y=0, width=1920, height=1080)

In [3]:
np.random.randn(10, 2)

array([[-0.08163882,  0.93064537],
       [ 0.66867895,  0.90126375],
       [-0.11418838, -1.19818542],
       [ 0.38564388,  1.99067814],
       [-0.45112349,  0.0988227 ],
       [-0.39059092, -0.04661867],
       [ 1.23282235, -1.69838374],
       [-0.09099695,  0.05209528],
       [ 0.74214564, -0.0655787 ],
       [-0.13501185, -0.87622391]])

In [4]:
Environment()


1. 0. 1. 2. 1.]
 [0. 0. 1. 2. 0.]
 [0. 2. 0. 0. 1.]
 [0. 0. 2. 1. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 1. 2. 1.]
 [0. 0. 1. 1. 0.]
 [0. 2. 0. 1. 1.]
 [0. 0. 2. 1. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 1. 2. 1.]
 [0. 0. 1. 1. 0.]
 [0. 2. 0. 1. 1.]
 [0. 1. 1. 1. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 2.]
 [0. 0. 1. 1. 0.]
 [0. 2. 0. 1. 1.]
 [0. 1. 1. 1. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 2.]
 [0. 0. 1. 1. 0.]
 [0. 2. 0. 1. 1.]
 [0. 1. 1. 1. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 2.]
 [0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 1.]
 [0. 1. 1. 1. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 2.]
 [0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 1.]
 [0. 1. 1. 1. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 2.]
 [0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 1.]
 [0. 1. 1. 1. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 2.]
 [0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 1.]
 [0. 1. 1. 1. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 2.]
 [0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 1.]
 [0. 1. 1. 1. 0.]]
[[0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 2.]
 [0. 1. 1. 1. 0.]
 [0. 1. 0. 2. 0.]
 [0. 1. 1. 1. 0.]]
[[0. 0. 0. 0. 0.]
 

In [5]:
import pyglet.text.formats.html as h
print(h._color_names)

{'black': [0, 0, 0, 255], 'silver': [192, 192, 192, 255], 'gray': [128, 128, 128, 255], 'white': [255, 255, 255, 255], 'maroon': [128, 0, 0, 255], 'red': [255, 0, 0, 255], 'purple': [128, 0, 128, 255], 'fucsia': [0, 128, 0, 255], 'green': [0, 255, 0, 255], 'lime': [255, 255, 0, 255], 'olive': [128, 128, 0, 255], 'yellow': [255, 0, 0, 255], 'navy': [0, 0, 128, 255], 'blue': [0, 0, 255, 255], 'teal': [0, 128, 128, 255], 'aqua': [0, 255, 255, 255]}
