In [1]:
import pyglet
from pyglet.window import mouse
from pyglet.window import key
import numpy as np
from Environment import Environment
from Agent import Agent
from time import time

In [2]:
pyglet.canvas.get_display().get_default_screen()

Win32Screen(x=0, y=0, width=1920, height=1080)

In [3]:
env = Environment()
env.make(3)

agent = Agent(env.cell_nb)

score_Hist = []
num_episodes = 100
num_actions = 100
for i in range(num_episodes):
    t0 = time()
    score = 0
    f_map = env.reset()
    episode_Hist = []
    for k in range(num_actions):
        actions = agent.choose_action(f_map)
        episode = env.step(actions)
        agent.learn(episode)
        score += episode["r"] if episode["r"] is float else 0
        episode_Hist.append(episode["r"])
    score_Hist.append(score)

    print(f"episode {i} with score {score}, which took {np.round(time() - t0, 3)}s")
    print(f"rewards {episode_Hist}")


stuck here 1 1, 1
stuck here 1 2, 2
stuck here 2 1, 1
stuck here 2 1, 1
stuck here 2 1, 1
Channel_loss after things [[1.85877037e-03 5.48788329e-05 1.05847797e-04]
 [5.48788329e-05 1.89075379e-03 2.12965330e-04]
 [1.05847797e-04 2.12965330e-04 2.01006867e-03]]
SINR : [[2.95294758e+11 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 8.87822350e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 6.30484914e+00]] 
DRL : [[0.00185877 0.         0.        ]
 [0.         0.00189075 0.        ]
 [0.         0.         0.00201007]]
CRL : [[0.00000000e+00 1.05847797e-04 5.48788329e-05]
 [0.00000000e+00 2.12965330e-04 5.48788329e-05]
 [0.00000000e+00 0.00000000e+00 3.18813127e-04]]
H : [[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]]
Power : [[0.30453584 0.         0.        ]
 [0.         0.37862822 0.        ]
 [0.         0.         0.64438736]]
OG CRL : [[0.00000000e+00 5.48788329e-05 1.05847797e-04]
 [5.48788329e-05 0.00000000e+00 2.12965330e-04]
 [1.05847797e-04 2.12965330e-04 0.00000000e+00]]


AttributeError: 'int' object has no attribute 'append'

In [4]:
import pyglet.text.formats.html as h
print(h._color_names)

{'black': [0, 0, 0, 255], 'silver': [192, 192, 192, 255], 'gray': [128, 128, 128, 255], 'white': [255, 255, 255, 255], 'maroon': [128, 0, 0, 255], 'red': [255, 0, 0, 255], 'purple': [128, 0, 128, 255], 'fucsia': [0, 128, 0, 255], 'green': [0, 255, 0, 255], 'lime': [255, 255, 0, 255], 'olive': [128, 128, 0, 255], 'yellow': [255, 0, 0, 255], 'navy': [0, 0, 128, 255], 'blue': [0, 0, 255, 255], 'teal': [0, 128, 128, 255], 'aqua': [0, 255, 255, 255]}
