In [1]:
import pyglet
from pyglet.window import mouse
from pyglet.window import key
from Device import Device
import numpy as np
from Swarm import Swarm

In [2]:
pyglet.canvas.get_display().get_default_screen()

Win32Screen(x=0, y=0, width=1920, height=1080)

In [3]:
np.random.randn(10, 2)

array([[-2.09094066,  0.48104913],
       [ 0.1013554 , -0.17821484],
       [ 0.19323651,  0.4283942 ],
       [-0.166919  ,  1.12107783],
       [ 1.18552553, -0.8968341 ],
       [-1.31090197,  0.93860144],
       [-0.81347816, -0.57447721],
       [ 1.15587488, -0.15710884],
       [ 2.43227771,  0.38563976],
       [ 0.38184101,  0.24416556]])

In [4]:
S = Swarm()
n_devices = 15
pos_L = np.random.randn(n_devices, 2)/2
init_L = [(pos, (0,0)) for pos in pos_L]
S.dList_init(init_L)
S.discretize()
S.render()

[[2. 0. 0. 0. 0.]
 [0. 3. 0. 0. 1.]
 [0. 0. 4. 0. 1.]
 [1. 1. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]
