In [1]:
import pyglet
from pyglet.window import mouse
from pyglet.window import key
from Device import Device
import numpy as np
from Swarm import Swarm

In [2]:
pyglet.canvas.get_display().get_default_screen()

Win32Screen(x=0, y=0, width=1920, height=1080)

In [3]:
np.random.randn(10, 2)

array([[ 0.06336524,  0.63642706],
       [-0.51736756,  1.7097386 ],
       [ 0.10475116, -0.95525176],
       [ 1.03104882,  0.48323643],
       [ 0.36071319, -0.43825063],
       [-0.10967718,  0.41754868],
       [-0.27802652,  0.61581355],
       [-0.87312643, -0.81662292],
       [-0.03830601,  1.23653021],
       [ 0.46430461, -1.420874  ]])

In [4]:
S = Swarm()
n_devices = 15
pos_L = np.random.randn(n_devices, 2)/2
init_L = [(pos, (0,0)) for pos in pos_L]
S.dList_init(init_L)
#S.discretize()
S.render()

[[0. 1. 1. 0. 0.]
 [0. 1. 3. 1. 0.]
 [1. 0. 2. 1. 1.]
 [0. 0. 2. 0. 0.]
 [0. 1. 0. 0. 0.]]


TypeError: __init__() got an unexpected keyword argument 'color'

In [ ]:
print(pyglet.text.formats.html)